version: '3.9'

services:
  db_auth:
    image: postgres:14.3-alpine
    container_name: db_auth
    restart: always
    env_file: .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: "exit 0"
